### ISSUE TITLE
`zencart/zencart` versioning crashes the build

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisoriesBuilder#735]
Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/actions/runs/5481781446
Ref: https://github.com/advisories/GHSA-c9r9-3h38-r7vj
Ref: https://packagist.org/packages/zencart/
Ref: https://packagist.org/packages/zencart/zencart

The advisory crashes this build due to the `< 1.5.5e`  constraint.

Note how @zencart has a really strange / non-compliant versioning scheme.

It even crashes @composer's package overview page 🤔

```

STDERR:
    
    In VersionParser.php line 521:
                                                                                   
      Could not parse version constraint < 1.5.5e: Invalid version string "1.5.5e  
      "                                                                            
                                                                                   
    
    validate [--no-check-all] [--check-lock] [--no-check-lock] [--no-check-publish] [--no-check-version] [-A|--with-dependencies] [--strict] [--] [<file>]
    
     in /home/runner/work/SecurityAdvisoriesBuilder/SecurityAdvisoriesBuilder/vendor/azjezz/psl/src/Psl/Shell/execute.php:180
Stack trace:
#0 /home/runner/work/SecurityAdvisoriesBuilder/SecurityAdvisoriesBuilder/build-conflicts.php(152): Psl\Shell\execute()
#1 /home/runner/work/SecurityAdvisoriesBuilder/SecurityAdvisoriesBuilder/build-conflicts.php(225): Roave\SecurityAdvisories\{closure}()
#2 /home/runner/work/SecurityAdvisoriesBuilder/SecurityAdvisoriesBuilder/build-conflicts.php(232): Roave\SecurityAdvisories\{closure}()
#3 {main}
```

**Comment by Ocramius** [comment]
Workaround in #736
