### ISSUE TITLE
“Could not parse version constraint” error

### ISSUE THREAD

**Issue by brandonkelly** [Roave/SecurityAdvisoriesBuilder#738]
I’m trying to run this script locally, however getting the following error:

```
    In VersionParser.php line 521:

      Could not parse version constraint < 3.1.33-dev-4: Invalid version string "3.1.33-dev-4"


    validate [--no-check-all] [--check-lock] [--no-check-lock] [--no-check-publish] [--no-check-version] [-A|--with-dependencies] [--strict] [--] [<file>]

     in /var/www/html/SecurityAdvisoriesBuilder/vendor/azjezz/psl/src/Psl/Shell/execute.php:175
Stack trace:
#0 /var/www/html/SecurityAdvisoriesBuilder/build-conflicts.php(152): Psl\Shell\execute('/usr/bin/php8.2', Array, '/var/www/html/S...')
#1 /var/www/html/SecurityAdvisoriesBuilder/build-conflicts.php(225): Roave\SecurityAdvisories\{closure}('/var/www/html/S...')
#2 /var/www/html/SecurityAdvisoriesBuilder/build-conflicts.php(232): Roave\SecurityAdvisories\{closure}()
#3 /var/www/html/SecurityAdvisoriesBuilder/update-security-advisories.php(46): require('/var/www/html/S...')
#4 /var/www/html/SecurityAdvisoriesBuilder/update-security-advisories.php(47): Roave\SecurityAdvisories\{closure}()
#5 /var/www/html/SecurityAdvisoriesBuilder/update-security-advisories.php(59): Roave\SecurityAdvisories\{closure}()
#6 {main}
```

**Comment by Ocramius** [comment]
Yep, duplicate of #737

**Comment by Ocramius** [comment]
Just merged a fix that **should** get this running again: give it a spin :)
